apiVersion: v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabel: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
  spec:
    containers:
      image: postgres:12-alpine
      name: postgres
      ports:
        containerPort: 5432
      env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valuseFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
      volumeMounts:
        name: postgres-volume-mount
        mountPath:
          /var/lib/postgresql/data
  volumes:
    name: postgres-volume-mount
    persistentVolumeClaim:
      claimName: postgres-pvc
